### PR TITLE
Adding functions related to clients reposting a Bluesky post

### PR DESCRIPTION
**Pull request by andylin2004**
## Description
This pull request implements the `createRepostRecord` and `deleteRepostRecord` functions for the ATProtoKit package to implement full support for users who want to repost Bluesky posts. 

## Linked Issues
None

## Type of Change
- [ ] Bug Fix
- [x] New Feature
- [ ] Documentation

## Checklist:
- [x] My code follows the [ATProtoKit API Design Guidelines](https://github.com/MasterJ93/ATProtoKit/blob/main/API_GUIDELINES.md) as well as the [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/).
- [x] I have performed a self-review of my own code and commented it, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings or errors in the compiler or runtime.
- [x] My code is able to build and run on my machine.
## Additional Notes
In my testing, using `deleteLikeRecord` with repost URIs works correctly, so the `deleteRepostRecord` just calls on the `deleteLikeRecord` function. I have commented this quirk in code, although I'm not too sure if theres minute details I'm missing out.

## Credits
If you want to be credited in the CONTRIBUTORS file, you can fill out the form below. Please don't remove the square brackets.
- Name: [Andy Lin]
- GitHub: [@andylin2004]
- Bluesky: [Replace with your Bluesky handle if you have one]

### CODE REVIEW

**Comment by MasterJ93** [comment]
Thank you _very_ much for making this for me. I appreciate it a lot! I have so much to do, so takes a bit of weight off my shoulders.

With respect to `deleteRepostRecord()`, I wasn't expecting `deleteLikeRecord()` to actually work for reposts as well. I feel like we can refactor that method to be more generic (so a `deleteRecord()` method), and then any `delete[record]Record()` method could simply invoke that private method. I guess this means that method will work regardless of the record, then. This is good.

**Comment by andylin2004** [comment]
I have edited the `deleteLikeRecord()` function to call a `deleteActionRecord()` (basically the old `deleteLikeRecord()` function). The `deleteActionRecord()` function is an internal function instead of an actual private method to prevent it from being called externally, but without the complier issues with private being too restrictive.

**Comment by rhysm94** [comment]
Ack, sorry, I should have checked open PRs before opening mine! Will close #61 😀

**Comment by MasterJ93** [comment]
No problem! I want to release this and a few other things as part of 0.21.0 some time next week, though there's a specific bug that I'm struggling to tackle right now. Please be patient. 🙏

**Review by MasterJ93 — APPROVED** [review]

**Pull request merged**
